---

galaxy_info:
  author: charlesrocket
  description: Git installer for Unix/Linux
  role_name: git
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: GenericUNIX
      versions:
        - all
    - name: GenericBSD
      versions:
        - all
    - name: GenericLinux
      versions:
        - all
  galaxy_tags:
    - development
    - git
    - system
